{ HOME: 
   { _H1: [ 'Home Design 3D - Free', '', '', '' ],
     _H2: 
      [ '',
        'iTunes is the world\'s easiest way to organize and add to your digital media collection.',
        'By Anuman',
        'Screenshots',
        'Customers Also Bought' ],
     _P: 
      [ '\n        We are unable to find iTunes on your computer. To download the free app Home Design 3D - Free by Anuman, get iTunes now.          \n      ',
        'Already have iTunes? Click I Have iTunes to open it now.',
        'Open iTunes to buy and download apps.',
        'With Home Design 3D, designing and remodeling your house in 3D has never been so quick and intuitive! Accessible to everyone, Home Design 3D is the reference interior design application for a professional result at your fingertips! CREATE, DESIGN, FURNISH AND DECORATE EASILY YOUR HOME AND SHARE IT WITH A COMMUNITY OF MORE THAN 30 MILLION OF USERS WORLDWIDE!-- FREE VERSION --In this FREE version, you can test the functionalities of the app and explore its possibilities.BE AWARE, SAVE FUNCTION IS NOT INCLUDED IN THIS FREE VERSION! However, projects created can be saved directly by in-app purchase. Whether you want to decorate, design or create the house of your dreams, Home Design 3D is the perfect app for you:1. DESIGN YOUR FLOORPLAN- In 2D and 3D, draw your plot, rooms, dividers- Change the height or the thickness of the walls, create corners - Add doors and windows  with fully-resizable pieces of joinery 2. FURNISH AND DECORATE- Design and decorate both the interior and outdoor of your home- Make your choice from over a thousand of pieces of furniture and accessories, customize your decoration and express your style, from the most classical to the trendiest! - Edit any object, by changing its size, color, position and altitude on the walls- Duplicate your favorite items thanks to the copy/paste function- Use the undo/redo feature at anytime if you want to go back-  Use the eye dropper to find an existing color in the plan - You can also import picture as texture and apply them everywhere3. VISUALIZE AND VISIT YOUR CREATION- Visit your creation in real-time 3D as if you were inside it thanks to our brand new photo-realistic 3D rendering- Discover your home, your outdoor and even your neighborhood- Admire the result day and night, the compass function will show you where exactly the light will fall at different times of the day4. IMPORT/EXPORT AND SHARE- Import any plan and display it on the background of the project- Export and continue your projects on your other devices thanks to the cross-platform compatibility - Share your projects via e-mail, Dropbox, OneDrive and many more file hosting services!- Share your best creations  with the Home Design 3D community on www.homedesign3d.net!Suitable for the iPad 4 and iPhone 4s or latestNo internet connection requiredIllustrated tutorial available Calling all professionals! We can make it possible to see your products in Home Design 3D, or develop a unique version of the app for your needs. Contact us at pro@anuman-interactive.com_________________________________________Follow us on Twitter @homedesign3dJoin us on facebook.com/homedesign3dGet inspired on our Pinterest boards/homedesign3d/',
        '- Possibility of proportionnally enlarge objects.- When scaling objects, the rotate button appears.- The compass is now available in 2D and 3D. - Objects that needed to be placed on walls can now be placed freely with and without the snap.- Several improvements - Bug fix- If you encounter any problems with the update, contact us at support@homedesign3d.net or through our Facebook page "Home Design 3D (Official)"',
        '\n    I got the full version of this app because I\'m having a house built in New Jersey and with this app I was able to modify the original plan that the builder offered to make. I was able to move the kitchen to the other side of the house as well as the powder room and the pantry, and I was able to visit the inside of how all that would look before construction. I was also able to plan out all my windows and doors which was a huge help. Plus email the architect all the screen shots. I would have rated higher but the app is a little short. It needs the ability to add measurement lines to any area. Back-splash for kitchens (which I rigged up with picture frames) and more common windows and doors. Also levels, like the garages here in jersey are usually lower than the house. And most important, default wall size. The houses out here are mostly 7&quot; exterior and 4&quot; interior. Also, it may get a little laggy sometimes. I have a new iPad air2 with the latest versions and it does the same as with my older iPad. But all that said, I would still buy it. It\'s been very helpful.\n  ',
        '\n    I love the app. It is extremely useful for interior design and renovation plans. I spent a lot of time designing my house because we are going through a renovation and I was trying different things with the specific measurements for it. I worked over multiple days with the app left open and I was very frustrated to find that after I left the app for a while I lost all my work! I would be happy if saving was an option in the free version as this is pretty much crucial for a time consuming activity such as this. It would be just fine to have less options for decor and furniture if saving was an option. I was not very happy AT ALL. The full price just isn\'t worth it in my opinion. If you\'re looking for a game with playable characters and the ability to design a house, I would buy any one of The Sims games. Even the old ones will let you save.\n  ',
        '\n    I visualize designs in my mind all the time but I can\'t draw to save my life.  When my hubby and I decided to start planning an extension on our house, I was trying to verbally describe everything I was picturing.  And while he was vey patient, it was frustrating for me.  I started researching design apps and found this one.  Even though it is pretty intuitive, it took a bit of time working in it to discover all the amazing things it could do above and beyond mapping out a space - like changing the colors and textures of anything I wanted to or giving an estimate of how many gallons of paint I would need.  My one and only complaint (which could be me still needing to learn) is I can\'t figure out how to add a second story.  Otherwise, I love it!!\n  ',
        'Compatibility: Requires iOS 8.0 or later. Compatible with iPhone, iPad, and iPod touch.',
        'Discover and share new apps.',
        'Follow us on @AppStore.',
        'Discover and share new music, movies, TV, books, and more.',
        'Follow us @iTunes and discover new iTunes Radio Stations and the music we love.' ],
     _IMGsrc: 
      [ 'https://s.mzstatic.com/images/web/itunes_preview/itunespreview_en@2x.png',
        '/images/web/ihaveitunes.png',
        '/images/web/freedownload.png',
        'http://a4.mzstatic.com/us/r30/Purple71/v4/4a/46/95/4a4695ce-6387-be80-1fa7-b0fdc15c6139/screen520x924.jpeg',
        'http://a2.mzstatic.com/us/r30/Purple71/v4/5e/cd/de/5ecdde09-0060-b063-6571-fb9db35556e5/screen520x924.jpeg',
        'http://a5.mzstatic.com/us/r30/Purple71/v4/fd/bf/7e/fdbf7e0e-3efc-cfd8-39bc-ff14da438b83/screen520x924.jpeg',
        'http://a5.mzstatic.com/us/r30/Purple71/v4/03/2b/0d/032b0d03-7a14-77a2-3a03-672293772913/screen520x924.jpeg',
        'http://a1.mzstatic.com/us/r30/Purple71/v4/94/2b/17/942b17c2-816a-91c2-c0d5-47e1e6fa1a65/screen520x924.jpeg',
        'http://a5.mzstatic.com/us/r30/Purple71/v4/62/ed/b0/62edb0cf-7132-e928-da0b-d87961013017/sc552x414.jpeg',
        'http://a3.mzstatic.com/us/r30/Purple71/v4/d9/73/c2/d973c235-1a97-0cae-ec65-3c93fdb51077/sc552x414.jpeg',
        'http://a3.mzstatic.com/us/r30/Purple71/v4/c7/a5/d2/c7a5d207-a85d-8559-c77c-2a93eade48b4/sc552x414.jpeg',
        'http://a3.mzstatic.com/us/r30/Purple71/v4/c9/fc/14/c9fc1441-a96f-392b-cd77-fd5c68b12279/sc552x414.jpeg',
        'http://a5.mzstatic.com/us/r30/Purple71/v4/6e/d9/69/6ed969d6-40f1-514a-bfd1-7db7a39a44e5/sc552x414.jpeg',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://s.mzstatic.com/htmlResources/249d/frameworks/images/p.png',
        'https://www.apple.com/itunes/shared/itunes-this-week/images/social_appstore_title.png',
        'https://www.apple.com/global/elements/itunesmodule/facebook_appstore_icon.png',
        'https://www.apple.com/itunes/shared/itunes-this-week/images/social_itunes_facebook_title.png',
        'https://www.apple.com/global/elements/itunesmodule/facebook_itunes_icon.png',
        'https://www.apple.com/itunes/shared/itunes-this-week/images/social_itunes_twitter_title.png',
        'https://www.apple.com/global/elements/itunesmodule/twitter_icon.png' ] },
  Insurance: 
   { _H1: [ 'Allstate&#174; Auto Insurance' ],
     _H2: 
      [ 'Enjoy Quality Car Insurance Coverage.',
        'Allstate Did You Know?' ],
     _P: 
      [ 'Enter a valid US ZIP Code to set your location.',
        'Select a product to get a quote.',
        'Edit location',
        'Retrieve a saved quote',
        'Log in to My Account',
        'Quality Car Coverage On And Off The Road.',
        'Find your local agentGet a quote',
        'Auto',
        'Find Your Local Agent',
        '',
        'Retrieve a saved quote',
        '24-hour support',
        '1-800-ALLSTATE',
        '(1-800-255-7828)',
        'With an Allstate auto policy, you\'ll get more than top-notch auto insurance. Enjoy many services and benefits that can help you:',
        'Find an agent to learn more about your benefits.',
        'Allstate car insurance gives you quality protection at a great price. Every policy comes with the support of a knowledgeable and friendly Allstate agent. With personal attention and service, you\'ll have the information you need to choose the car insurance coverage that makes the most sense for you. ',
        '\r\n            Enter your zip code\r\n          See auto insurance requirements in your state.\r\n        ',
        '1 of 5',
        'Consider these steps to take after a car accident: First thing, take care of yourself and others. Find out if  [&#8230;]',
        'Read the full story',
        'Your Allstate agent can help you buy with confidence, get guaranteed savings, and enjoy an even easier car buying experience.',
        'Explore offers ',
        'Consider these steps to take after a car accident: First thing, take care of yourself and others. Find out if  [&#8230;]',
        'Read the full story',
        'Your Allstate agent can help you buy with confidence, get guaranteed savings, and enjoy an even easier car buying experience.',
        'Explore offers ',
        'Enter a valid US ZIP Code to set your location.',
        'Retrieve a saved quote',
        '&copy; 2017 Allstate Insurance Company',
        'Set Your Location' ],
     _IMGsrc: 
      [ '/resources/images/back-to-top.svg',
        '/resources/images/search_on.png',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/Allstate/images/global/logo-allstate-sm.png',
        '/resources/Allstate/images/global/logo-allstate.png',
        '/resources/Allstate/images/global/icons/icon-tertiary-auto.png',
        '/resources/images/allstate_binoculars_grey_icon.svg',
        '/resources/images/allstate_close_icon.svg',
        '/resources/images/allstate_binoculars_icon.svg',
        '/resources/Images/InsuranceStateMap/map.png',
        '/resources/Allstate/images/carousel/auto-car1-accident-260x150.jpg',
        '/resources/Allstate/images/home-page/features/car-buying-service-auto-overview.jpg',
        '/resources/Allstate/images/carousel/auto-car1-accident-260x150.jpg',
        '/resources/Allstate/images/home-page/features/car-buying-service-auto-overview.jpg',
        '/resources/Allstate/redesign/img/logo_footer.png',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/ResponsiveTopNavigation/img_trans.gif',
        '/resources/images/adchoice_1_1.png',
        '/resources/Images/error.svg',
        '/resources/Images/error.svg',
        '/resources/Images/pin.png',
        '/resources/Images/error.svg',
        '/resources/images/progress.gif' ] },
  Loans: 
   { _H1: 
      [ 'Credit Cards',
        'Banking',
        'Investing',
        'Mortgages',
        'Loans',
        'Insurance',
        'Credit Cards',
        'Banking',
        'Investing',
        'Mortgages',
        'Loans',
        'Insurance',
        'Estimated loan offers for $5,000' ],
     _H2: 
      [ 'Review',
        'Compare',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Learn',
        'Review',
        'Compare',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Calculate',
        'Learn',
        'Review',
        'Compare',
        'Learn',
        'Loading your loans...' ],
     _P: 
      [ '\nA personal loan is an installment loan that is not backed by collateral such as a house or car. It differs from a mortgage or car loan in that the lender cannot directly seize your assets if you fail to pay back the loan. Your credit score still will be damaged if you default, though.',
        'What lenders are looking for: Any reputable lender will check your credit history and ask about your income and debt when deciding whether to offer you a loan. Your credit history directly affects the interest rate you are offered, and so does your ability to repay the loan. Rates do vary from lender to lender, but here is what interest rates on personal loans look like, on average:',
        '',
        'How’s Your Credit?Score RangeEstimated APRExcellent720 - 85010.94%Good690 - 71914.56%Average630 - 68919.84%Bad580 - 62928.64%Poor579 and belowUnlikely to qualify',
        'Someone with poor or average credit may be able to get an unsecured personal loan on the strength of a steady income and low debt levels. Someone with excellent credit and a low debt-to-income ratio may be offered interest rates as low as those seen on secured loans.',
        'Almost all lenders will require you to be 18 or older and a legal U.S. resident, with a verifiable bank account and not in bankruptcy or foreclosure.',
        'What about lenders that don’t check your credit? Some lenders have no minimum credit score requirements, but that does not mean they don’t check your credit report. They do.',
        'You may have seen lenders that offer loans with no credit check at all, but they will charge interest rates of 300% or more, as will a payday lender.',
        'Only a few lenders will approve a loan for borrowers with poor credit scores. Expect rates toward the higher end of the range — that is, up to 36% — if your credit is damaged. If you can’t qualify for a loan through a reputable lender, don’t head for a payday lender. Consider these options first.',
        'Pros of personal loans',
        'Consolidation for your credit cards and other debts. A personal loan can be used to consolidate high-interest credit card debt into one payment at a  lower interest rate and accelerate debt payoff.',
        'Improved credit score. You may improve your credit score by moving revolving credit card debt to an installment loan, because you lower your credit utilization ratio and diversify your types of debt.',
        'Cons of personal loans',
        'Higher interest rates than secured loans and (some) credit cards. If you have excellent credit and can pay off the debt in 12 to 18 months, you can likely get a credit card that has 0% interest on balance transfers for a year or longer. Alternatively, if you are a homeowner, home equity loans often have lower interest rates than personal loans. But be cautious; you’re risking your house by putting it up as collateral.',
        'Extended application process. The approval process for a loan can last a few days and may require more information than that needed to get a credit card.',
        'Is a personal loan right for you?',
        'Personal loans work best as part of a longer-term plan to improve your finances.',
        'Borrow to consolidate debt if it means you’ll get out of debt more quickly. Borrow for a wedding or a vacation if you are confident you can make the payments.',
        'But don’t borrow to put off the inevitable. If you aim to become debt-free, create a plan to do so. If you can’t handle your current debt, investigate your debt-relief options.',
        'Once you decide a personal loan is a good choice for you, calculate payments at a range of interest rates and amounts so you’ll have an idea of what to expect as you shop.',
        'If you have good credit and an existing banking relationship, it’s worth checking out the offerings from your current provider or local credit union.',
        'The lenders who partner with NerdWallet follow Consumer Financial Protection Bureau standards for installment lending, with interest rates no higher than 36% (widely considered the upper limit of affordability) and consideration of your credit history and ability to repay. NerdWallet has reviewed their application processes and verified their underwriting guidelines.',
        'Check out our choices',
        'Best debt consolidation loans',
        'Best personal loans for good credit',
        'Best bad credit loans',
        'Personal loans with co-signers',
        'Secured personal loans',
        'Personal loans for home improvement',
        'Loans presented on this page have a minimum loan length of 1 year, maximum loan length of 7 years, and a maximum APR 36.00%.',
        'Disclaimer: NerdWallet strives to keep its information accurate and up to date. This information may be different than what you see when you visit a financial institution, service provider or specific product’s site. All financial products, shopping products and services are presented without warranty. When evaluating offers, please review the financial institution’s Terms and Conditions. Pre-qualified offers are not binding. If you find discrepancies with your credit score or information from your credit report, please contact TransUnion® directly.',
        'Additionally, this site may be compensated through third party advertisers. However, the results of our comparison tools, blog content and editorial reviews are based on objective analysis. For more information, please see our Advertiser Disclosure.' ],
     _IMGsrc: 
      [ '//assets.nerdwallet.com/img/nw-logos/nerdwallet-logo-new.png',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lightstream.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lightstream.gif',
        'https://cdn.nerdwallet.com/img/logos/NW_Logo_Vert_RGB_Screen.png',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/mobilePrequalCard2.png',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/bestegg.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/bestegg.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/upstart.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/upstart.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/discover.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/discover.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/prosper.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/prosper.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/payoff.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/payoff.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/freedomfinancial.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/freedomfinancial.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lendingpoint.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lendingpoint.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lendingclub.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/lendingclub.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/rocketloans.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/rocketloans.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/avant.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/avant.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/mariner.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/mariner.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/pioneer.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/pioneer.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/iloan.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/iloan.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/onemain.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/onemain.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/ascend.gif',
        'https://cdn.nerdwallet.com/img/diy/personal-loans/ascend.gif',
        'https://cdn.nerdwallet.com/img/icons/global-footer/Download_on_the_App_Store_Badge_US-UK_135x40.svg',
        'https://play.google.com/intl/en_us/badges/images/badge_new.png',
        '//cdn.nerdwallet.com/img/logos/NW_Logo_N_Logomark.svg',
        '/lib/opt.gif',
        'https://www.facebook.com/tr?id=612184065591075&ev=PageView&noscript=1',
        '//pixel.quantserve.com/pixel/p-P4DS8qXcrRU2Q.gif' ] },
  Attorney: { _H1: [], _H2: [], _P: [], _IMGsrc: [] },
  Mortgage: { _H1: [], _H2: [], _P: [], _IMGsrc: [] },
  Lawyer: { _H1: [], _H2: [], _P: [], _IMGsrc: [] },
  Credit: 
   { _H1: [],
     _H2: 
      [ 'Always there when you need it.',
        'Find a Location',
        'PaymentCalculator',
        'How it Works',
        'Manage My Account',
        'CareCredit Mobile App',
        'Pay My Provider',
        'Get Your FREE Financing Guide' ],
     _P: 
      [ 'Use the CareCredit healthcare credit card for your life needs - even for your pets.',
        'By providing your email address, you consent to receive marketing email communications from CareCredit.',
        '© document.write(current_year); Synchrony Bank. All Rights Reserved.',
        '© document.write(current_year); Synchrony Bank. All Rights Reserved.' ],
     _IMGsrc: 
      [ '/assets/pages/home/banner-1.jpg',
        '/assets/pages/home/cc_ShareYourStory_HeroBanner_11292016.jpg',
        '/assets/pages/home/cc_RiteAid_Heart_HeroBanner_01312017.png',
        '/assets/pages/home/cc_Bowflex_Partners_HeroBanner_02012017.png',
        '/assets/pages/home/video-2.png',
        '/assets/views/home/mobile/apply.png',
        '/assets/views/home/mobile/manage-account.png',
        '/assets/views/home/mobile/find-doctor.png',
        '/assets/views/home/mobile/payment-calc.png',
        '/assets/views/home/mobile/procedures.png',
        '/assets/views/home/mobile/how-it-works.png',
        '/assets/views/home/mobile/company.png',
        '/assets/views/home/mobile/faqs.png',
        '/assets/doctor-locator/img/structure/help-icon-white.png',
        'https://www.facebook.com/tr?id=1828534484033223&ev=PageView&noscript=1' ] },
  Donate: 
   { _H1: [ '', 'Donate', '' ],
     _H2: [ 'Java script not enabled?  ' ],
     _P: [ '', '' ],
     _IMGsrc: 
      [ 'https://cdn.movember.com/uploads/images/Global/foundation-header-logo.png',
        'https://cdn.movember.com/uploads/images/Mo%20Space/Default%20Profile%20Pics/MoBro_Tiny.gif',
        'https://cdn.movember.com/uploads/images/Donate/Mov_Found_New.png' ] },
  Degree: { _H1: [], _H2: [], _P: [], _IMGsrc: [] },
  Hosting: 
   { _H1: [ '�������� ������� ������' ],
     _H2: 
      [ '��������� ��&nbsp;���� ������:',
        '�������������� ������:',
        '��������� ��&nbsp;���� ������:',
        '�������������� ������:',
        '��������� ��&nbsp;���� ������:',
        '�������������� ������:',
        '������� ������ ��� ���������� CMS',
        '������������ ��� �������� ��&nbsp;�������� REG.RU',
        '������� ������',
        '�������������� ����������' ],
     _P: 
      [ '\n                        ��������������������\n                        ',
        '\n                            ���������� MySQL-���\n                        ',
        '\n                        ������������������ ������\n                        ',
        '\n                        ������\n                        ',
        '\n                    SSL-�������������������\n                    ',
        '\n                        ������ ��&nbsp;DDoS\n                        ',
        '\n                            ������� ������������ ���������&nbsp;���������. ������� �������\n                        ',
        '\n                        �����������������\n                        ',
        '\n                        �������Google AdWords\n                        ',
        '\n                        \n                          ���������PHP\n                        \n\n\n                        ',
        '������ ������������������                        ',
        '������ VIP-������ �������� ���&nbsp;���, ��� ������� ������� ����������� �������, ��&nbsp;�� ����� ������� ����� ��&nbsp;����������������� VPS-�������. ������ ���������� �������� �&nbsp;������� SSD ����� ��������� ���������� ������ ������������ ���-�������.',
        '\n        REG.RU ������������� ���������� SSL-���������� ���&nbsp;���� ������� ��������, ������� �&nbsp;Host-0,����� ���������� ����� �������� �������� ������ �&nbsp;������� ��&nbsp;������� �������������.\n    ',
        '\n        ������ �������� ��&nbsp;����������� �������� �������� ������� ����������� �&nbsp;������ ���������.��. ������������ �&nbsp;��������.\n        ',
        '��� ����� ������ �&nbsp;������� ������?������ �&nbsp;help-��� ���&nbsp;������ ���������.\n        ',
        '�������� REG.RU&nbsp;&mdash; ����� ����� ���������� ������������� �������� ���� �&nbsp;�������-�����������. ��� �������� �������������� ������ �&nbsp;������������������� �&nbsp;30 ������� ���. ���������, ��� ��� ��&nbsp;���������� 10 ���, ������ �&nbsp;������ ��������� ��&nbsp;������ ��������, ������� ����� ����������� �&nbsp;������ �� ���������� ���&nbsp;������� ������������. ��&nbsp;����� �&nbsp;��, ��� ������� ���� ����������� ������� ����������, �&nbsp;���������� ����� ������ ����������� ���&nbsp;����� ���-������������: ����������� �������� ���� �&nbsp;750+ ��������� �����, ������� ����� ����� �&nbsp;������� ��������, ������������ �&nbsp;������� ������, ������� ������� ��&nbsp;CMS (Joomla, WordPress, &laquo;1C-�������&raquo;),',
        'SSL-����������� �&nbsp;������ ������, ������� ������� ��� �&nbsp;�������� �������� �&nbsp;����������� ������ �&nbsp;����.',
        '������ �������� ��&nbsp;������� �������� ��������������� ��������, ���� ��&nbsp;����� ������� ������������� �&nbsp;����������� ������ ���-�������. ��&nbsp;10 ��� ���� ����� �&nbsp;��������-������� ��� �������� ����� 1.3 ��� ��������, �&nbsp;����� ���������� ��������� ����� �������� 21 ���. ��&nbsp;���������� �������, ��� ������ REG.RU&nbsp;&mdash; ������ ��&nbsp;������������ ��� ��&nbsp;������ ����� ���� �&nbsp;�������.',
        '�������� ������� ��&nbsp;REG.RU&nbsp;&mdash; ��� ��&nbsp;������ ����������� ���������� ��&nbsp;�������-���������� �1 �&nbsp;������. ��� ��� �&nbsp;����������� ����� ������� ����������� ������� ���&nbsp;������ ������ �������� �&nbsp;�������� �������������� ������ �&nbsp;�������. ���, ��� ����� ���&nbsp;����, ����� ������� ���� �&nbsp;������������ �������� �&nbsp;��������� ���&nbsp;������������� ������ ������&nbsp;&mdash; ��&nbsp;�������� ��&nbsp;��������������. �������� ����, ���������������� ������� �������� ������, ����������� ������, ������� ��&nbsp;Windows ���&nbsp;Linux, ������� ������ ���� �&nbsp;������������, ���������� SSL-�����������, ��������� ���������� CMS, ������� ������ ����������, ������ ��&nbsp;������� �&nbsp;�����, �������������� ���������� ������� ������� FTP, ���������� ����� �&nbsp;��.',
        '�� ����������� ��������� Linux-��������� ��������� ������ ���������� ������:\n\t\t\t(e��� �&nbsp;������ ��� ������ CMS, ��&nbsp;������ �������� ����������� ��&nbsp;���������\n\t\t\t�&nbsp;������ ����������� ��������� ��������)\n\t\t\n\t\t',
        '���&nbsp;���� ���������� CMS �������� REG.RU ������������� ����������� �������� �����:',
        '        ���� ������� � ������ ��� 18% ��&nbsp;������� ������ ������ ��&nbsp;36&nbsp;���.    ',
        '\n    \n        ��� ����� ��&nbsp;���������, ����������� ��&nbsp;�����, ���������� �&nbsp;������������ �&nbsp;����������������� ��. ��� ����� ����������������������� ����� ���������� �������� �����������. �������� �����, �������� �&nbsp;����� �����, ����������� ��&nbsp;������ �����,�������� �������������� ��� &laquo;����������� �������� ���� ���.��&raquo; ��� ������� ���.\n    \n    ',
        '\n        �&nbsp;������ �������������� �&nbsp;�������������� �������������� �������� Agava �&nbsp;REG.RU ���������� ���� ������ �&nbsp;������� �������������� ����� �������� �&nbsp;����������� �������. �&nbsp;5.12.2016�. ��� ����������� ��������� �&nbsp;������������ ����������� ������������� REG.RU, ������� ���������� ������� ���.\n    ' ],
     _IMGsrc: 
      [ '/i/svg/b-header__logo_site_ru.svg',
        '/i/icon/hosting/joomla_medium.png',
        '/i/icon/hosting/wordpress_medium.png',
        '/i/icon/hosting/drupal_medium.png',
        '/i/icon/hosting/bitrix_medium.png',
        '/i/icon/hosting/netcat_medium.png',
        '/i/icon/hosting/umi_medium.png',
        '/i/icon/hosting/host_medium.png',
        '/i/icon/hosting/abo_medium.png',
        '/i/icon/hosting/dle_medium.png',
        '//mc.yandex.ru/watch/1379221',
        '//mc.yandex.ru/watch/4919539',
        'https://www.facebook.com/tr?id=741445972583669&ev=PageView&noscript=1',
        '//googleads.g.doubleclick.net/pagead/viewthroughconversion/1025813086/?value=0&amp;label=m_gmCNKwvAQQ3tSS6QM&amp;guid=ON&amp;script=0',
        '//top-fwz1.mail.ru/counter?id=2569367;js=na' ] },
  Claim: { _H1: [], _H2: [], _P: [], _IMGsrc: [] },
  Startups: 
   { _H1: [ 'The national enterprise campaign', 'Join the StartUp Tour' ],
     _H2: 
      [ 'I-COM Data Startup Challenge 2017',
        'Top 5 Tips For Launching a Business in the UK',
        '5 Steps to Doing Your Own PR (and getting results)' ],
     _P: 
      [ 'StartUp Britain is a campaign by entrepreneurs, for entrepreneurs. We offer inspiration, resources and guidance to help people start and grow their own business.',
        'Learn More',
        'StartUp Britain is hitting the road again this summer to provide free advice and support to thousands of aspiring entrepreneurs.',
        'Learn More',
        'Sponsored by',
        'Powered by',
        'startups created this year!',
        '',
        '',
        '',
        'StartUp Britain is delighted to announce its partnership with the I-COM Data Startup Challenge 2017. The I-COM summit will take place in the enchanting city of Porto, Portugal, April 24th-27th, 2017. More information about the event, including how to enter, can ',
        ' read more',
        'Despite what a you might hear, the UK is a great place to launch a business. There’s lots of opportunity and support available for you, you just need to go out and take it. ',
        'PR as we know it is changing. Less elusive and increasingly accessible, it’s now entirely possible for businesses to do their own PR without the need for 50-strong team of staff and a six-figure budget. No one is better at ',
        ' read more',
        'Sponsored by',
        'Powered by' ],
     _IMGsrc: 
      [ 'http://startupbritain.org/wp-content/uploads/2015/12/main-logo.png',
        'http://startupbritain.org/wp-content/uploads/2015/12/main-logo.png',
        'http://startupbritain.org/wp-content/uploads/2015/12/cfe-logo.png',
        'http://startupbritain.org/wp-content/uploads/2015/12/cfe-logo.png',
        'http://startupbritain.org/wp-content/plugins/LayerSlider/static/img/blank.gif',
        'http://startupbritain.org/wp-content/plugins/LayerSlider/static/img/blank.gif',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/support.png',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/resources.png',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/bus.png',
        'http://startupbritain.org/wp-content/uploads/2017/01/1B4Bt8Wk-225x175.jpeg',
        'http://startupbritain.org/wp-content/uploads/2016/12/Gl0xhQtt-225x175.jpg',
        'http://startupbritain.org/wp-content/uploads/2016/12/Image2-e1482224347848-225x175.jpg',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/twitter.png',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/fb.png',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/linkedin.png',
        'http://176.32.230.249/startupbritain.org/wp-content/uploads/2015/12/google-plus-icon-01.png',
        'http://startupbritain.org/wp-content/uploads/2015/12/footer-cfe-logo-white.png' ] } }